### ISSUE TITLE
Labels don't switch language without restart/re-entering area

### ISSUE THREAD

**Issue by Vegechu** [wlewisgames/caveblazers-translations#7]
Challenge names and descriptions don't switch language without restart.

Card names, description, positives and negatives don't switch until you leave and re-enter the arena room.

Object labels in the main and arena room don't switch until re-entering.

**Comment by Vegechu** [comment]
Card names, description, positives and negatives, as well as the "Build" label of the equipment below the portal don't switch either, until you leave and re-enter the arena room.

**Comment by wlewisgames** [comment]
Fixed in v1.3.1a, thanks!

**Comment by Vegechu** [comment]
Object labels like "Pumice Crystal" or "Custom Mode" still don't switch.

**Comment by Vegechu** [comment]
Adding blessings & their descriptions in the levels to this.
